[2024-07-23T05:41:23.821+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_braching_etl_daily.transform_and_load_task manual__2024-07-23T05:41:11.983489+00:00 [queued]>
[2024-07-23T05:41:23.833+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_braching_etl_daily.transform_and_load_task manual__2024-07-23T05:41:11.983489+00:00 [queued]>
[2024-07-23T05:41:23.834+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-23T05:41:23.859+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_and_load_task> on 2024-07-23 05:41:11.983489+00:00
[2024-07-23T05:41:23.871+0000] {standard_task_runner.py:60} INFO - Started process 5614 to run task
[2024-07-23T05:41:23.876+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_braching_etl_daily', 'transform_and_load_task', 'manual__2024-07-23T05:41:11.983489+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/test_braching.py', '--cfg-path', '/tmp/tmpam8ia_z1']
[2024-07-23T05:41:23.878+0000] {standard_task_runner.py:88} INFO - Job 299: Subtask transform_and_load_task
[2024-07-23T05:41:23.941+0000] {task_command.py:423} INFO - Running <TaskInstance: test_braching_etl_daily.transform_and_load_task manual__2024-07-23T05:41:11.983489+00:00 [running]> on host 087c584822ad
[2024-07-23T05:41:24.037+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_braching_etl_daily' AIRFLOW_CTX_TASK_ID='transform_and_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T05:41:11.983489+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-23T05:41:11.983489+00:00'
[2024-07-23T05:41:24.038+0000] {logging_mixin.py:188} INFO - Start data transformation and load stage
[2024-07-23T05:41:24.576+0000] {pipeline_options.py:923} WARNING - Bucket specified in temp_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.
[2024-07-23T05:41:25.007+0000] {pipeline_options.py:923} WARNING - Bucket specified in staging_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.
[2024-07-23T05:41:25.757+0000] {pipeline_options.py:923} WARNING - Bucket specified in temp_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.
[2024-07-23T05:41:26.446+0000] {pipeline_options.py:923} WARNING - Bucket specified in staging_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.
[2024-07-23T05:41:26.734+0000] {stager.py:800} INFO - Executing command: ['/usr/local/bin/python', '-m', 'build', '--no-isolation', '--sdist', '--outdir', '/tmp/tmpa_unl4ha', '/opt/***/plugins']
[2024-07-23T05:41:26.887+0000] {stager.py:810} INFO - Executing command: ['/usr/local/bin/python', 'setup.py', 'sdist', '--dist-dir', '/tmp/tmpa_unl4ha']
[2024-07-23T05:41:29.627+0000] {dataflow_runner.py:397} INFO - Pipeline has additional dependencies to be installed in SDK worker container, consider using the SDK container image pre-building workflow to avoid repetitive installations. Learn more on https://cloud.google.com/dataflow/docs/guides/using-custom-containers#prebuild
[2024-07-23T05:41:29.630+0000] {environments.py:314} INFO - Using provided Python SDK container image: gcr.io/cloud-dataflow/v1beta3/beam_python3.8_sdk:2.57.0
[2024-07-23T05:41:29.630+0000] {environments.py:321} INFO - Python SDK container image set to "gcr.io/cloud-dataflow/v1beta3/beam_python3.8_sdk:2.57.0" for Docker environment
[2024-07-23T05:41:29.746+0000] {apiclient.py:663} INFO - Starting GCS upload to gs://ingestion_layer/staging/test-braching-bigquery-etl.1721713289.736155/workflow.tar.gz...
[2024-07-23T05:41:30.670+0000] {apiclient.py:673} INFO - Completed GCS upload to gs://ingestion_layer/staging/test-braching-bigquery-etl.1721713289.736155/workflow.tar.gz in 0 seconds.
[2024-07-23T05:41:30.671+0000] {apiclient.py:663} INFO - Starting GCS upload to gs://ingestion_layer/staging/test-braching-bigquery-etl.1721713289.736155/submission_environment_dependencies.txt...
[2024-07-23T05:41:31.254+0000] {apiclient.py:673} INFO - Completed GCS upload to gs://ingestion_layer/staging/test-braching-bigquery-etl.1721713289.736155/submission_environment_dependencies.txt in 0 seconds.
[2024-07-23T05:41:31.255+0000] {apiclient.py:663} INFO - Starting GCS upload to gs://ingestion_layer/staging/test-braching-bigquery-etl.1721713289.736155/pipeline.pb...
[2024-07-23T05:41:31.902+0000] {apiclient.py:673} INFO - Completed GCS upload to gs://ingestion_layer/staging/test-braching-bigquery-etl.1721713289.736155/pipeline.pb in 0 seconds.
[2024-07-23T05:41:31.922+0000] {pipeline_options.py:339} WARNING - Unknown pipeline options received: celery,worker. Ignore if flags are used for internal purposes.
[2024-07-23T05:41:31.942+0000] {pipeline_options.py:339} WARNING - Unknown pipeline options received: celery,worker. Ignore if flags are used for internal purposes.
[2024-07-23T05:41:33.663+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_braching.py", line 86, in transform_and_load_task
    odd_numbers | 'ProcessOdd' >> beam.Map(process_odd_numbers)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 613, in __exit__
    self.result = self.run()
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 560, in run
    return Pipeline.from_runner_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 587, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 502, in run_pipeline
    self.dataflow_client.create_job(self.job), self)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/utils/retry.py", line 298, in wrapper
    return fun(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 721, in create_job
    return self.submit_job_description(job)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/utils/retry.py", line 298, in wrapper
    return fun(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 839, in submit_job_description
    raise DataflowJobAlreadyExistsError(
apache_beam.runners.dataflow.internal.apiclient.DataflowJobAlreadyExistsError: There is already active job named test-braching-bigquery-etl with id: 2024-07-22_22_41_31-2563151932984575308. If you want to submit a second job, try again by setting a different name using --job_name.
[2024-07-23T05:41:33.696+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_braching_etl_daily, task_id=transform_and_load_task, execution_date=20240723T054111, start_date=20240723T054123, end_date=20240723T054133
[2024-07-23T05:41:33.724+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 299 for task transform_and_load_task (There is already active job named test-braching-bigquery-etl with id: 2024-07-22_22_41_31-2563151932984575308. If you want to submit a second job, try again by setting a different name using --job_name.; 5614)
[2024-07-23T05:41:33.768+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-23T05:41:33.787+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
