[2024-07-22T07:55:17.650+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fact_order.transform_and_load_task manual__2024-07-22T07:55:11.863805+00:00 [queued]>
[2024-07-22T07:55:17.663+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fact_order.transform_and_load_task manual__2024-07-22T07:55:11.863805+00:00 [queued]>
[2024-07-22T07:55:17.665+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-22T07:55:17.684+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_and_load_task> on 2024-07-22 07:55:11.863805+00:00
[2024-07-22T07:55:17.692+0000] {standard_task_runner.py:60} INFO - Started process 9586 to run task
[2024-07-22T07:55:17.698+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fact_order', 'transform_and_load_task', 'manual__2024-07-22T07:55:11.863805+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/fact_order.py', '--cfg-path', '/tmp/tmpp_vxv0_x']
[2024-07-22T07:55:17.701+0000] {standard_task_runner.py:88} INFO - Job 215: Subtask transform_and_load_task
[2024-07-22T07:55:17.772+0000] {task_command.py:423} INFO - Running <TaskInstance: fact_order.transform_and_load_task manual__2024-07-22T07:55:11.863805+00:00 [running]> on host 087c584822ad
[2024-07-22T07:55:17.877+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fact_order' AIRFLOW_CTX_TASK_ID='transform_and_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T07:55:11.863805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T07:55:11.863805+00:00'
[2024-07-22T07:55:17.886+0000] {pipeline.py:197} INFO - Missing pipeline option (runner). Executing pipeline using the default runner: DirectRunner.
[2024-07-22T07:55:19.105+0000] {pipeline_options.py:372} WARNING - Discarding unparseable args: ['celery', 'worker']
[2024-07-22T07:55:19.106+0000] {pipeline_options.py:390} WARNING - Discarding invalid overrides: {'save_main_sesion': True}
[2024-07-22T07:55:19.190+0000] {statecache.py:234} INFO - Creating state cache with size 104857600
[2024-07-22T07:55:23.391+0000] {bundle_processor.py:237} ERROR - unconverted data remains: .000000 [while running 'RemoveDuplicates/RemoveDuplicates']
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1435, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 639, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1611, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "/opt/airflow/plugins/my_modules/transformation_load_stage.py", line 35, in _remove_duplicates
    latest_record = max(grouped_elements, key = lambda elem: int(time.mktime(datetime.strptime(elem['last_updated_at'], "%Y-%m-%d %H:%M:%S").timetuple())))
  File "/opt/airflow/plugins/my_modules/transformation_load_stage.py", line 35, in <lambda>
    latest_record = max(grouped_elements, key = lambda elem: int(time.mktime(datetime.strptime(elem['last_updated_at'], "%Y-%m-%d %H:%M:%S").timetuple())))
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: .000000
[2024-07-22T07:55:23.407+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1435, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 639, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1611, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "/opt/airflow/plugins/my_modules/transformation_load_stage.py", line 35, in _remove_duplicates
    latest_record = max(grouped_elements, key = lambda elem: int(time.mktime(datetime.strptime(elem['last_updated_at'], "%Y-%m-%d %H:%M:%S").timetuple())))
  File "/opt/airflow/plugins/my_modules/transformation_load_stage.py", line 35, in <lambda>
    latest_record = max(grouped_elements, key = lambda elem: int(time.mktime(datetime.strptime(elem['last_updated_at'], "%Y-%m-%d %H:%M:%S").timetuple())))
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: .000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fact_order.py", line 72, in transform_and_load_task
    (
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 613, in __exit__
    self.result = self.run()
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 587, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/direct/direct_runner.py", line 128, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 204, in run_pipeline
    self._latest_run_result = self.run_via_runner_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 228, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 483, in run_stages
    bundle_results = self._execute_bundle(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 811, in _execute_bundle
    self._run_bundle(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1048, in _run_bundle
    result, splits = bundle_manager.process_bundle(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1384, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 384, in push
    response = self.worker.do_instruction(request)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 656, in do_instruction
    return getattr(self, request_type)(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 694, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1119, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 237, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 569, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 571, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 262, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 265, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 952, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 953, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1437, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1547, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1435, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 639, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1611, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "/opt/airflow/plugins/my_modules/transformation_load_stage.py", line 35, in _remove_duplicates
    latest_record = max(grouped_elements, key = lambda elem: int(time.mktime(datetime.strptime(elem['last_updated_at'], "%Y-%m-%d %H:%M:%S").timetuple())))
  File "/opt/airflow/plugins/my_modules/transformation_load_stage.py", line 35, in <lambda>
    latest_record = max(grouped_elements, key = lambda elem: int(time.mktime(datetime.strptime(elem['last_updated_at'], "%Y-%m-%d %H:%M:%S").timetuple())))
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: .000000 [while running 'RemoveDuplicates/RemoveDuplicates']
[2024-07-22T07:55:23.439+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=fact_order, task_id=transform_and_load_task, execution_date=20240722T075511, start_date=20240722T075517, end_date=20240722T075523
[2024-07-22T07:55:23.475+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 215 for task transform_and_load_task (unconverted data remains: .000000 [while running 'RemoveDuplicates/RemoveDuplicates']; 9586)
[2024-07-22T07:55:23.512+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-22T07:55:23.540+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
