[2024-07-16T16:27:03.806+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T16:26:55.612700+00:00 [queued]>
[2024-07-16T16:27:03.820+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T16:26:55.612700+00:00 [queued]>
[2024-07-16T16:27:03.821+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-16T16:27:03.851+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_and_load_task> on 2024-07-16 16:26:55.612700+00:00
[2024-07-16T16:27:03.861+0000] {standard_task_runner.py:60} INFO - Started process 1589 to run task
[2024-07-16T16:27:03.866+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_product', 'transform_and_load_task', 'manual__2024-07-16T16:26:55.612700+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/dim_product_orchestration.py', '--cfg-path', '/tmp/tmpi0ow4v80']
[2024-07-16T16:27:03.868+0000] {standard_task_runner.py:88} INFO - Job 103: Subtask transform_and_load_task
[2024-07-16T16:27:03.941+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T16:26:55.612700+00:00 [running]> on host d3d5a4009625
[2024-07-16T16:27:04.045+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_product' AIRFLOW_CTX_TASK_ID='transform_and_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T16:26:55.612700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T16:26:55.612700+00:00'
[2024-07-16T16:27:04.857+0000] {pipeline_options.py:923} WARNING - Bucket specified in temp_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.
[2024-07-16T16:27:05.213+0000] {pipeline_options.py:923} WARNING - Bucket specified in staging_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.
[2024-07-16T16:27:07.015+0000] {pipeline_options.py:923} WARNING - Bucket specified in temp_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.
[2024-07-16T16:27:07.268+0000] {pipeline_options.py:923} WARNING - Bucket specified in staging_location has soft-delete policy enabled. To avoid being billed for unnecessary storage costs, turn off the soft delete feature on buckets that your Dataflow jobs use for temporary and staging storage. For more information, see https://cloud.google.com/storage/docs/use-soft-delete#remove-soft-delete-policy.
[2024-07-16T16:27:07.572+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dim_product_orchestration.py", line 59, in transform_and_load_task
    (
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 613, in __exit__
    self.result = self.run()
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 560, in run
    return Pipeline.from_runner_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 587, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 395, in run_pipeline
    artifacts = environments.python_sdk_dependencies(options)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/transforms/environments.py", line 905, in python_sdk_dependencies
    return stager.Stager.create_job_resources(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/stager.py", line 279, in create_job_resources
    raise RuntimeError(
RuntimeError: The file ./setup.py cannot be found. It was specified in the --setup_file command line option.
[2024-07-16T16:27:07.599+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dim_product, task_id=transform_and_load_task, execution_date=20240716T162655, start_date=20240716T162703, end_date=20240716T162707
[2024-07-16T16:27:07.616+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 103 for task transform_and_load_task (The file ./setup.py cannot be found. It was specified in the --setup_file command line option.; 1589)
[2024-07-16T16:27:07.656+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T16:27:07.686+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
